# phonemize config

default_language: en-us
default_language_sr: en-US
default_tld: com

backend: espeak

language_map_sr: 
  de: de
  it: it
  fr-fr: fr
  pt-pt: pt
  pt-br: pt-br
  en-us: en-us
  en-gb: en-uk
  es: es
  es-la: es-ar

language_map_t2s:
  de: de
  it: it
  fr-fr: fr
  pt-pt: pt
  pt-br: pt-br
  en-us: en-us
  en-gb: en-uk
  es: es
  es-la: es-ar

tld_map_t2s:
  br: com.br # brasil (pt)
  pt: pt # portugal (pt)
  ar: com.ar # argentina (es)
  us: us # united states (en)
  uk: co.uk # united kingdom (en)

lang_validation:
  es: 
    - es
    - es-la
  en: 
    - en-us
    - en-gb
  fr: 
    - fr-fr
  de: 
    - de
  it: 
    - it
  pt: 
    - pt-pt
    - pt-br


  
unknownvalueerror: Google Speech Recognition could not understand audio

requesterror: Could not request results from Google Speech Recognition service

