[build]
# Instala Python y pip, luego instala los requerimientos
command = """
apt-get update && apt-get install -y python3 python3-pip
pip install -r requirements.txt
"""

[start]
# Inicia el servidor Uvicorn
command = "uvicorn app:app --reload --port 8000 --host 0.0.0.0"
