[build]
command = """
apt-get update && apt-get install -y software-properties-common 
add-apt-repository ppa:deadsnakes/ppa 
apt-get update &&
apt-get install -y python3.9 python3.9-venv python3.9-dev ffmpeg 
python3.9 -m venv venv 
. venv/bin/activate 
pip install -r requirements.txt
"""

[start]
command = ". venv/bin/activate && uvicorn app:app --reload --port 8000 --host phonemix-model.up.railway.app"
